### ISSUE TITLE
Unable to install bcrypt

### ISSUE THREAD

**Issue by bmnidhin** [Bilguun132/nodejs-authentication#1]
node index.js
(node:6692) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Listening on port 3000...
(node:6692) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Connected to MongoDB...
(node:6692) UnhandledPromiseRejectionWarning: ReferenceError: bcrypt is not defined
    at router.post (E:\Nidhin Projects\Web\nodejs\entry-auth\routes\user.route.js:26:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aditya2712** [comment]
Please Use BcryptJs .
You just need to install bcryptJs instead of bcrypt.
use 
# npm uninstall bcrypt
then 
# npm -i bcryptjs
After installing it.
Replace the line
# "const bcrypt = require('bcypt');"
with 
# "const bcrypt = require('bcyptjs');"
and leave the rest of the code as it is.

**Comment by bmnidhin** [comment]
thank you 💯
